SRC = writer.c
CC = $(CROSS_COMPILE)gcc

all: $(TARGET)
	$(CC) $(SRC) -o writer
#	cc writer.c -o writer

#CROSS_COMPILE:
#	aarch64-none-linux-gnu-gcc writer.c -o writer

clean:
	rm -f writer.o writer
